jobs:
  syncWorker:
    schedule: '*/2 * * * *' # Every 2 minutes
    command: curl -sS -X POST -H "Content-Type: application/json" --data "{}" https://xgvaibxxiwfraklfbwey.supabase.co/functions/v1/sync-worker

  enrichAssetsYahoo:
    schedule: '*/15 * * * *' # Turbo: every 15 minutes (processes BATCH_SIZE assets per run)
    command: curl -sS -X POST -H "Content-Type: application/json" --data "{}" https://xgvaibxxiwfraklfbwey.supabase.co/functions/v1/enrich-assets-yahoo

  backfillAssetHistory:
    schedule: '7,22,37,52 * * * *' # Turbo: every 15 minutes, staggered
    command: curl -sS -X POST -H "Content-Type: application/json" --data "{}" https://xgvaibxxiwfraklfbwey.supabase.co/functions/v1/backfill-asset-history

  backfillPostLinks:
    schedule: '*/10 * * * *' # Every 10 minutes
    command: curl -sS -X POST -H "Content-Type: application/json" --data "{}" "https://xgvaibxxiwfraklfbwey.supabase.co/functions/v1/fix-posts?only_missing_trader_id=true&limit=200&offset=0"

  fetchDailyPrices:
    schedule: '10 20 * * *' # Daily 20:10 UTC (adjust to your market close)
    command: curl -sS -X POST -H "Content-Type: application/json" --data "{}" "https://xgvaibxxiwfraklfbwey.supabase.co/functions/v1/fetch-daily-prices?max_assets=250"

  scrapeDailyMovers:
    schedule: '30 20 * * *' # Daily 20:30 UTC (after fetch-daily-prices)
    command: curl -sS -X POST -H "Content-Type: application/json" --data "{}" https://xgvaibxxiwfraklfbwey.supabase.co/functions/v1/scrape-daily-movers
